blank_issues_enabled: false
contact_links:
  - name: LLM CLI Discussions
    url: https://github.com/gnana997/llm/discussions
    about: Ask questions and discuss ideas with the community
  - name: LLM CLI Documentation
    url: https://github.com/gnana997/llm/blob/master/README.md
    about: Check our documentation for usage and examples
  - name: Want to contribute?
    url: https://github.com/gnana997/llm/blob/master/CONTRIBUTING.md
    about: Read our contribution guidelines before submitting PRs
